# -*- coding: utf-8 -*-
"""pct1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WLYQVMYcKwO3vgSatRF7LzbMI7AC6DWj
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
print("np and pd are okay")

import sklearn
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

df = pd.read_csv("/content/Bengaluru_House_Data.csv", usecols=["size","society","total_sqft","bath","balcony","price"])

df

df.info()

df.shape

df.describe()

df.isnull().sum()

df.loc[:,"total_sqft"]= pd.to_numeric(df["total_sqft"],errors='coerce')

df["room_size"] = df["size"].str.split().str[0]
df["room_type"] = df["size"].str.split().str[1]

df.dtypes

df.drop(columns=["size","society"],inplace=True)

df.sample(10)

df.isnull().mean()*100

df.sample(5)

x_train,x_test,y_train,y_test = train_test_split (
    df.drop(columns=["price"]),
    df["price"], test_size = 0.2, random_state = 2)

x_train

y_train

x_test

x_train

imputer1 = SimpleImputer(strategy="most_frequent")
imputer2 = SimpleImputer(strategy="mean")

trf=ColumnTransformer([
    ("imputer1",imputer1,['room_type']),
    ("imputer2",imputer2,["room_size","total_sqft","bath","balcony"])
],remainder="passthrough",verbose_feature_names_out=False)

trf.fit(x_train)

trf.set_output(transform="pandas")
x_train_trf=trf.transform(x_train)
x_test_trf=trf.transform(x_test)

ohe= OneHotEncoder(handle_unknown="ignore", sparse_output=False)
trf2=ColumnTransformer([
("ohe",ohe,["room_type"])],
remainder="passthrough",verbose_feature_names_out=False)

trf2.set_output(transform="pandas")
x_train_trf=trf2.fit_transform(x_train_trf)
x_test_trf=trf2.transform(x_test_trf)

trf3=ColumnTransformer([
  ("scaler",StandardScaler(),["room_size","total_sqft","bath","balcony"])],
  remainder="passthrough",verbose_feature_names_out=False)

trf3.set_output(transform="pandas")
trf3.fit_transform(x_train_trf)
trf3.transform(x_test_trf)

x_train_trf.isnull().sum()

x_test_trf.isnull().sum()

x_train_trf.dtypes

sns.relplot(data=x_train_trf, x="room_size", y=y_train, height=10,aspect=2,kind= "scatter")

sns.displot( data=x_train_trf, x= "balcony",kind='kde')

sns.displot(data=x_train_trf, x="balcony",kind='hist',bins=5)

sns.displot(data=x_train_trf, x="room_size", y='balcony',kind='hist',height=11, aspect=1.6)

sns.catplot(data=x_train_trf,x="room_size",y="bath",kind='strip',aspect=2,height=11)

sns.catplot(data=x_train_trf, x='balcony',kind='count')

sns.catplot(data=x_train_trf,x='bath',kind='box')

sns.catplot(data=x_train_trf,x='total_sqft',kind='box')

clf=LinearRegression()
clf.fit(x_train_trf,y_train)
y_pred=clf.predict(x_test_trf)
r2_score(y_test,y_pred)

